// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCwwLE_yOG4BzNfWNdJwAbUWs_WX6CZzo',
    appId: '1:415821992607:web:397713998c7341e25308aa',
    messagingSenderId: '415821992607',
    projectId: 'exercise7a-f283d',
    authDomain: 'exercise7a-f283d.firebaseapp.com',
    storageBucket: 'exercise7a-f283d.appspot.com',
    measurementId: 'G-NVZWNH60BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV5LRZZhJw2RlFekc06iNy1MBEfJgnICY',
    appId: '1:415821992607:android:431d745f880bf00a5308aa',
    messagingSenderId: '415821992607',
    projectId: 'exercise7a-f283d',
    storageBucket: 'exercise7a-f283d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiMO3IHhv9QYERC2mjKnj6fyrVjYIgJM0',
    appId: '1:415821992607:ios:04ef599e5af03b295308aa',
    messagingSenderId: '415821992607',
    projectId: 'exercise7a-f283d',
    storageBucket: 'exercise7a-f283d.appspot.com',
    iosBundleId: 'com.example.exercise5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiMO3IHhv9QYERC2mjKnj6fyrVjYIgJM0',
    appId: '1:415821992607:ios:04ef599e5af03b295308aa',
    messagingSenderId: '415821992607',
    projectId: 'exercise7a-f283d',
    storageBucket: 'exercise7a-f283d.appspot.com',
    iosBundleId: 'com.example.exercise5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCwwLE_yOG4BzNfWNdJwAbUWs_WX6CZzo',
    appId: '1:415821992607:web:6a069c1ea969d68c5308aa',
    messagingSenderId: '415821992607',
    projectId: 'exercise7a-f283d',
    authDomain: 'exercise7a-f283d.firebaseapp.com',
    storageBucket: 'exercise7a-f283d.appspot.com',
    measurementId: 'G-NS3LCFNTCS',
  );
}
