// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXAdAWBmwE_pWsX85U9qXgmO5MoGowhnc',
    appId: '1:546906534772:web:8d795cf6d4ad26ce393221',
    messagingSenderId: '546906534772',
    projectId: 'info6350-final-project-15f36',
    authDomain: 'info6350-final-project-15f36.firebaseapp.com',
    storageBucket: 'info6350-final-project-15f36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQwIX62273VjKgtotWbRcUJkxwWmQP55Q',
    appId: '1:546906534772:android:86415660a2656425393221',
    messagingSenderId: '546906534772',
    projectId: 'info6350-final-project-15f36',
    storageBucket: 'info6350-final-project-15f36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT0MMEP8E8McPY-DKBo-wiBbZum3F_d4A',
    appId: '1:546906534772:ios:b5b27a9ce574d136393221',
    messagingSenderId: '546906534772',
    projectId: 'info6350-final-project-15f36',
    storageBucket: 'info6350-final-project-15f36.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT0MMEP8E8McPY-DKBo-wiBbZum3F_d4A',
    appId: '1:546906534772:ios:b5b27a9ce574d136393221',
    messagingSenderId: '546906534772',
    projectId: 'info6350-final-project-15f36',
    storageBucket: 'info6350-final-project-15f36.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXAdAWBmwE_pWsX85U9qXgmO5MoGowhnc',
    appId: '1:546906534772:web:9755c4915323a8a8393221',
    messagingSenderId: '546906534772',
    projectId: 'info6350-final-project-15f36',
    authDomain: 'info6350-final-project-15f36.firebaseapp.com',
    storageBucket: 'info6350-final-project-15f36.appspot.com',
  );

}