// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXC7BdiVXN1JHA_R2bB4QWBJri3qMpQQ0',
    appId: '1:333506735799:web:f20bc30c806959537de732',
    messagingSenderId: '333506735799',
    projectId: 'fir-flutter-codelab-d5228',
    authDomain: 'fir-flutter-codelab-d5228.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d5228.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdOAZmIOWmL8yLPMNtWgGdXllpRhyCYo',
    appId: '1:333506735799:android:fd3f1fe0725a747e7de732',
    messagingSenderId: '333506735799',
    projectId: 'fir-flutter-codelab-d5228',
    storageBucket: 'fir-flutter-codelab-d5228.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzSugof3lvcXNgYBe6Ri1W8Rr5abaDAQU',
    appId: '1:333506735799:ios:4c545a71075abb0c7de732',
    messagingSenderId: '333506735799',
    projectId: 'fir-flutter-codelab-d5228',
    storageBucket: 'fir-flutter-codelab-d5228.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzSugof3lvcXNgYBe6Ri1W8Rr5abaDAQU',
    appId: '1:333506735799:ios:4c545a71075abb0c7de732',
    messagingSenderId: '333506735799',
    projectId: 'fir-flutter-codelab-d5228',
    storageBucket: 'fir-flutter-codelab-d5228.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
